# =============================================================================
# PROJECT:      SteamMachine-DIY - Complete Dynamic Configuration
# VERSION:      1.0.0 - YAML Architecture
# DESCRIPTION:  Full Gamescope parameters mapping (Converted from Manifesto).
# PHILOSOPHY:   KISS (Keep It Simple, Stupid) - Hardcore Libre Mode
# PATH:         $HOME/.config/steamos_diy/config.yaml
# LICENSE:      MIT
# =============================================================================

env_vars:
  GAME_WRAPPER: ""
  GAME_EXTRA_ARGS: ""
flags:
